FROM microsoft/aspnetcore:2.0 AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/aspnetcore-build:2.0 AS build
WORKDIR /src
COPY CoreAPI/CoreAPI.csproj CoreAPI/
RUN dotnet restore CoreAPI/CoreAPI.csproj
COPY . .
WORKDIR /src/CoreAPI
RUN dotnet build CoreAPI.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish CoreAPI.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "CoreAPI.dll"]
